/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 cyber_car.gltf --transform 
Files: cyber_car.gltf [29.39MB] > C:\Users\soora\Downloads\Assets\cyberpunk_car\cyber_car-transformed.glb [563.62KB] (98%)
Author: 4d_Bob (https://sketchfab.com/3d_Bob)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-car-b4301ff99d214d16a7a43708a5866bf0
Title: Cyberpunk car
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./cyber_car-transformed.glb')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cb_car_export_cb_car_0.geometry} material={materials.cb_car} rotation={[Math.PI, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/cyber_car-transformed.glb')
