/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 macintosh.gltf --transform 
Files: macintosh.gltf [485.66KB] > C:\Users\soora\Downloads\Assets\macintosh\macintosh-transformed.glb [38.4KB] (92%)
Author: Brian Seoane (https://sketchfab.com/dgrafi.seoane)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macintosh-f58b4bb7fb62402ea56782a46b4b481b
Title: Macintosh
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/macintosh-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane_0.geometry} material={materials.CremitaMac} position={[-0.013, 0, -0.037]} rotation={[0, 0.401, 0]} scale={0.03} />
      <mesh geometry={nodes.Cylinder_0.geometry} material={materials['Material.002']} position={[-0.089, -0.249, -0.218]} rotation={[-Math.PI / 2, 0, 0.401]} scale={[0.014, 0.014, 0.006]} />
      <mesh geometry={nodes.Cube_0.geometry} material={materials['Material.001']} position={[-0.14, -0.145, 0.016]} rotation={[-Math.PI / 2, 0, 0.401]} scale={[0.011, 0.001, 0.011]} />
      {/* <mesh geometry={nodes.Plane001_0.geometry} material={materials['Material.006']} position={[-0.019, 0.06, -0.063]} rotation={[0, 0.401, 0]} scale={[0.142, 0.108, 0.071]} /> */}
    </group>
  )
}

useGLTF.preload('/macintosh-transformed.glb')
